spring.application.name=smart-campus-event-management
server.port=3000

spring.data.mongodb.uri=mongodb://localhost:27017/smartcampus
spring.data.mongodb.auto-index-creation=true

spring.thymeleaf.cache=false

app.admin.username=vijayyy@gmail.com
app.admin.password=131605
app.student.username=student
app.student.password=student123
