spring.application.name=smart-campus-event-management
server.port=${PORT:3000}

spring.data.mongodb.uri=${MONGODB_URI:mongodb://localhost:27017/smartcampus}
spring.data.mongodb.auto-index-creation=true

spring.thymeleaf.cache=false
